name: Create Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  create-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext zip jq

      - name: Build Plasmoid
        run: |
          make build

      - name: Prepare Release Asset
        id: asset
        run: |
          VERSION=$(jq -r '.KPlugin.Version' package/metadata.json)
          ASSET_NAME="FancyTasksNG.plasmoid"
          mv release/FancyTasksNG.plasmoid "$ASSET_NAME"
          echo "asset_path=$ASSET_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          awk -v ver="[${VERSION}]" '/^## / { if (index($0, ver) > 0) { flag = 1; next } else if (flag) { flag = 0 } } flag' CHANGELOG.md > release_notes.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ steps.asset.outputs.asset_path }}
          name: Release ${{ github.ref_name }}
          body_path: release_notes.txt
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
